services:
  - docker
script:
  - docker login --username="$HEROKU_USERNAME" --password="$HEROKU_TOKEN" registry.heroku.com
  - docker build -t registry.heroku.com/supernotes/web .
  - docker push registry.heroku.com/supernotes/web
