services:
  - docker
script:
  - docker login --username="$HEROKU_USERNAME" --password="$HEROKU_TOKEN" registry.heroku.com
  - docker build -t registry.heroku.com/young-earth-66509/web .
  - docker push registry.heroku.com/young-earth-66509/web
