version: '3'
services:
  notes:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://mongo:27017/notes
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
